wandermart/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('<slug:order>/', views.order_detail, name='order_page'),
    path('place/<int:product_id>/', views.place_order, name='place_order')
]

wandermart/product_post/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView 

app_name = 'product_post'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:product>/', views.product_detail, name='product_detail'),
    path('login/', views.AccountLogin, name='loginformpage'),
    path('logout/', views.logout_view, name='logout'),
    #path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register_view, name='register'),
    path('search/', views.product_search, name="product_search")
]

wandermart/wandermart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('product_post.urls', 'product_post'), namespace='product_post')),
    path('store/', include(('storefront.urls', 'storefront'), namespace='storefront')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wandermart/product_post/models.py
from django.db import models
from storefront.models import Storefront
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.utils import timezone
from django.db.models import Avg
from cloudinary.models import CloudinaryField
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import UploadedFile

from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

# product listing status choices
PRODUCT_LISTING_STATUS_CHOICES = (
    ('draft','Draft'),
    ('published','Published'),
    ('archived','Archived'),
) 


####### CLOUDINARY
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 10  # 10mb


def file_validation(file):
    if not file:
        raise ValidationError("No file selected.")

    # For regular upload, we get UploadedFile instance, so we can validate it.
    # When using direct upload from the browser, here we get an instance of the CloudinaryResource
    # and file is already uploaded to Cloudinary.
    # Still can perform all kinds on validations and maybe delete file, approve moderation, perform analysis, etc.
    if isinstance(file, UploadedFile):
        if file.size > FILE_UPLOAD_MAX_MEMORY_SIZE:
            raise ValidationError("File shouldn't be larger than 10MB.")

## https://cloudinary.com/documentation/python_sample_projects


################# Product Listing
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField()
    store = models.ForeignKey(Storefront, on_delete=models.CASCADE)
    stock = models.BigIntegerField()
    publish = models.DateTimeField(default=timezone.now)
    dateadded = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) 
    slug = models.SlugField(max_length=250, unique_for_date='publish') # for URL purposes
    status = models.CharField(max_length=10, choices=PRODUCT_LISTING_STATUS_CHOICES, default='draft')
    #image = models.ImageField(upload_to='products/', null=True, blank=True)
    image = CloudinaryField('image',validators=[file_validation], null=True, blank=True)
    avg_rating = models.FloatField(default=0.0)
    published = PublishedManager()

    tags = TaggableManager()

    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-avg_rating','price']

    # absolute page url
    def get_absolute_url(self):
        return reverse("product_post:product_detail", args=[
            self.publish.year, 
            self.publish.month, 
            self.publish.day, 
            self.slug])

# product reviews
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=1, validators=[MinValueValidator(1),MaxValueValidator(5)])
    text = models.TextField()
    dateadded = models.DateField(auto_now_add=True)
    dateupdated = models.DateField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('dateadded',)
    
    def __str__(self):
        return f'Comment by {self.user} on {self.product}'
    
    # average rating change
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.product.avg_rating = self.product.reviews.aggregate(Avg('rating'))['rating__avg']
        self.product.save()

wandermart/product_post/forms.py
from django import forms
from .models import Review
from django.contrib.auth.models import User
from django.shortcuts import reverse
from .exceptions import LoginRequired
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class SearchForm(forms.Form):
    query = forms.CharField(required=False, max_length=255)

class ReviewForm(forms.ModelForm):

    # Your other form fields
    '''rating = forms.IntegerField()
    text = forms.Textarea()
    user = forms.CharField(widget=forms.HiddenInput(), required=False)'''

    class Meta:
        model = Review
        fields = ('rating','text')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        if self.request and not self.request.user.is_authenticated:
            raise LoginRequired("You must be logged in to submit a review.")
        return cleaned_data

    def save(self, commit=True):
        review = super().save(commit=False)
        if self.request and self.request.user.is_authenticated:
            review.user = self.request.user
        if commit:
            review.save()
        return review


#### REGISTRATION
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)


### LOGIN
class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})) # Optional

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user_cache = None  # For internal use by AuthenticationForm methods

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            from django.contrib.auth import authenticate
            self.user_cache = authenticate(username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    'Please enter a correct username and password. Note that both fields may be case-sensitive.',
                    code='invalid_login',
                )
            elif not self.user_cache.is_active:
                raise forms.ValidationError(
                    'This account is inactive.',
                    code='inactive',
                )
        return self.cleaned_data

    def get_user(self):
        return self.user_cache

wandermart/product_post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Review
from storefront.models import Storefront
from django.contrib.auth.models import User
from .exceptions import LoginRequired
# pagination
from django.views.generic import ListView
from taggit.models import Tag

# le forms
from .forms import ReviewForm, LoginForm, RegistrationForm, SearchForm #UserCreationForm
from django.contrib.postgres.search import SearchVector
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


# Create your views here.
def product_list(request):
    products = Product.published.all()
    searchform = SearchForm()

    return render(request, 'product_post/product/list.html', {"products": products, "searchform":searchform})

def product_search(request):
    searchform = SearchForm()
    query = None
    products = []
    tag_products = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            products = Product.published.annotate(
                search=SearchVector('name', 'description'),
            ).filter(search=query)

            # find products based on tags
            tag_products = Product.published.filter(tags__name__contains=query)

    return render(request, 'product_post/product/search.html',
            {'searchform':searchform, 'products':products, 'query':query, 'tag_products':tag_products})

@login_required(login_url='product_post:loginformpage')
def product_detail(request, year, month, day, product):
    product = get_object_or_404(Product, slug=product, status='published', 
            publish__year = year,
            publish__month = month,
            publish__day = day
            )
    
    #reviews
    reviews = product.reviews.filter(active=True)
    new_review = None

    # get similar products, limit the query to 5 objects because our layout wouldnt have enough space
    # and im too lazy to add a scrollable bar that will also contain an update function for the user to keep scrolling
    product_tags = product.tags.values_list('name', flat=True)
    similar_products = Product.objects.exclude(id=product.id).filter(tags__name__in=product_tags).distinct()[:5]
    
    if request.method == "POST":
        #review_form = ReviewForm(data=request.POST, user=request.user)
        review_form = ReviewForm(data=request.POST, request=request)


        if review_form.is_valid():
            new_review = review_form.save(commit=False)

            new_review.product = product
            new_review.user = request.user

            new_review.save()

    else:
        #review_form = ReviewForm(user=request.user)
        review_form = ReviewForm()

    return render(request, 'product_post/product/detail.html', 
            {"product": product, 'reviews': reviews, 'new_review':new_review, 'review_form': review_form, 'similar_products':similar_products})


class ProductListView(ListView):
    queryset = Product.published.all()
    context_object_name = "products"
    paginate_by = 10
    template_name = "product_post/product/list.html"



##### LOGIN

# check if user logged in
def AccountLogin(request):

    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, f"Successfully logged in as {user.username}!")
            return redirect('/')
        else:
            messages.error(request, "Invalid username or password.")
    else:
        login_form = LoginForm()
    return render(request, 'product_post/login.html', {'login_form': login_form})
    
    '''if request.method == "POST":
        login_form = LoginForm(data=request.POST)
    
    else:
        login_form = LoginForm()

    return render(request, 'product_post/login.html', {"login_form":login_form})'''


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Successfully logged out!")
    else:
        messages.info(request, "You are already logged out.")
    return redirect("product_post:product_list")

    '''logout(request)
    messages.success(request, "Successfully logged out!")
    return redirect(request, 'product_post/product/list.html')'''


##### REGISTER
def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Account created successfully!")
            return redirect('product_post:product_list')
        else:
            for error in form.errors.values():
                for msg in error:
                    messages.error(request, msg)
    else:
        form = RegistrationForm()
    return render(request, 'product_post/register.html', {'form':form})

wandermart/product_post/templates/product_post/product/detail.html
{% extends "product_post/base.html" %}
{% load static %}

{% block title %} {{ product.name }} {% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/product_post/product_detail.css' %}">
    <h1> {{product.name}} </h1>
    <p class="date">
        Listed: {{ product.publish }} by {{ product.store }}
    </p>
    <p> Average Rating: {{product.avg_rating}} </p>

    <img src="{{product.image.url}}" width=500, height=500>

    <!-- Place post details here -->
    <p class="description">
        {{ product.description }}
    </p> 

    <a href="{% url 'order:place_order' product.id %}"> Buy </a>

    {% with reviews.count as total_reviews %}
        <h3> Reviews: {{ total_reviews }} </h3>
    {% endwith %}

    <!-- SIMILAR PRPODUCTASFSDSZCZSA -->
    <h3>Similar Products </h3>
    <table>
        <tr>
            {% for similar_product in similar_products %}
            <td>
                <img src="{{similar_product.image.url}}" alt="{{similar_product.name}}" width=50 height=50>
                <h5><a href="{{ similar_product.get_absolute_url }}">{{ similar_product.name }}</a></h5>
                <p> Rating: {{ similar_product.avg_rating }} </p>
            </td>

            {% empty %}
            <td>
                <h5>There are no similar products </h5>
            <td>
            {% endfor %}
        </tr>
    </table>


    <!-- REVIEWS LIST -->
    <!-- will consider adding pagination if I have the motivation -->
    {% for review in reviews %}
    <div class="review">
        <p class="user">
            {{ review.user }} <span class="date">{{ review.dateadded }}</span>
        </p>
        <p class="rating">
            {{ review.rating }} out of 5
        </p>
        <p class="reviewtext">
            {{ review.text }}
        </p>
    {% empty %}
    <p class="emptyreviews">There are no reviews yet.</p>

    {% endfor %}

    <!-- USER -->
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.username }}! <a href="{% url 'product_post:logout' %}">Logout</a></p>
    {% else %}
        <p><a href="{% url 'product_post:loginformpage' %}">Login</a></p>
    {% endif %}

    <!-- REVIEW FORM -->
    {% if new_review %}
        <h3> Your review has been added. </h3>
    {% else %}
        <h2> Add a new Review </h2>
        <form class="reviewform" method="post">
            {{ review_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add Review"></p>
        </form>
    {% endif %}


{% endblock %}

wandermart/product_post/templates/product_post/product/list.html
{% extends "product_post/base.html" %}
{% load static %}

{% block title %}Wandermart: Aesthetic Marketplace{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'product_post/css/list_product.css' %}">
<script src="{% static 'product_post/js/animation.js' %}"></script> 
<!-- Fullscreen Hero Section -->
<section class="storefront-intro">
    <div class="intro-content">
        <h1>Welcome to Wandermart!</h1>
        <p>Finding the international products, brought closer to you</p>
        <button class="start-shopping" onclick="window.location.href='/store'">🛍️ Start Shopping</button>
        <div class="scroll-down">
            <span>Scroll Down ▼</span>
        </div>
    </div>

    <!-- Animated Images -->
    <div class="image-container">
        <img src="{% static 'product_post/images/snack1.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack2.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack3.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack4.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack5.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack6.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack7.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack8.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack9.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack10.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack11.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack12.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack13.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack14.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack15.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack16.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack17.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack18.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack19.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack20.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack21.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack22.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack23.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack24.png' %}" class="hero-image hidden">
        <img src="{% static 'product_post/images/snack25.png' %}" class="hero-image hidden">
    </div>
</section>


<!-- Product Grid -->
<div class="container">
    {% for product in products %}
        <div class="product_card">
            <div class="image-wrapper">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product_image">
            </div>
            <h2><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
            <p class="date">Listed: {{ product.publish }}</p>
            <p class="stock">Stock: {{ product.stock }}</p>
            {% if product.stock > 0 %}
                <button class="buy_now" onclick="window.location.href='product.get_absolute_url'">Buy Now</button>
            {% else %}
                <button class="out_of_stock" disabled>Out of Stock</button>
            {% endif %}
        </div>
    {% endfor %}
</div>

{% include "product_post/pagination.html" with page=page_obj %}
{% include "product_post/footer.html" with page=page_obj %}

{% endblock %}

wandermart/product_post/templates/product_post/product/search.html
{% extends "product_post/base.html" %}
{% load static %}

{% block title %}Wandermart: Aesthetic Marketplace{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'product_post/css/list_product.css' %}">

<!-- Product Grid -->
<h3> You searched for {{ query }} </h3>

<div class="container">
    {% for product in products %}
       
        <div class="product_card">
            <div class="image-wrapper">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product_image">
            </div>
            <h2><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
            <p class="date">Listed: {{ product.publish }}</p>
            <p class="stock">Stock: {{ product.stock }}</p>
            {% if product.stock > 0 %}
                <button class="buy_now" onclick="window.location.href='product.get_absolute_url'">Buy Now</button>
            {% else %}
                <button class="out_of_stock" disabled>Out of Stock</button>
            {% endif %}
        </div>

    {% empty %}
        <h2>We couldn't find any related products </h2>


    {% endfor %}
</div>

<h3> Search Results based on {{ query}} as tag </h3>
<div class="container">
    {% for tag_product in tag_products %}
       
        <div class="product_card">
            <div class="image-wrapper">
                <img src="{{ tag_product.image.url }}" alt="{{ tag_product.name }}" class="product_image">
            </div>
            <h2><a href="{{ tag_product.get_absolute_url }}">{{ tag_product.name }}</a></h2>
            <p class="date">Listed: {{ tag_product.publish }}</p>
            <p class="stock">Stock: {{ tag_product.stock }}</p>
            {% if tag_product.stock > 0 %}
                <button class="buy_now" onclick="window.location.href='tag_product.get_absolute_url'">Buy Now</button>
            {% else %}
                <button class="out_of_stock" disabled>Out of Stock</button>
            {% endif %}
        </div>

    {% empty %}
        <h2>We couldn't find any related products </h2>


    {% endfor %}
</div>


{% include "product_post/footer.html" with page=page_obj %}

{% endblock %}